// video-archiver-react/src/components/IdentityHeader.tsx
import { useContext } from "react";
import { Link, useNavigate } from "react-router-dom";
import { AuthContext } from "../routes/Root";
import { DecodedJWT } from "../dto/identity/DecodedJWT";
import { IRefreshToken } from "../dto/identity/IRefreshToken";
import { IdentityService } from "../services/IdentityService";

const IdentityHeader = () => {
    const { jwt, setJwt, refreshToken, setRefreshToken, setSelectedAuthor } = useContext(AuthContext);
    const navigate = useNavigate();
    
    const identityService = new IdentityService();

    const logout = async () => {
        setJwt!(null);
        setRefreshToken!(null);
        setSelectedAuthor!(null);
        if (jwt && refreshToken) {
            await identityService.logout(jwt, refreshToken);
        }
        navigate("/");
    }

    if (jwt && refreshToken) {
        return (
            <>
                <li className="nav-item">
                    <UserInfo jwt={jwt} refreshToken={refreshToken} />
                </li>
                <li className="nav-item">
                    <button onClick={(e) => {
                        e.preventDefault();
                        logout();
                    }} className="nav-link text-dark">Logout</button>
                </li>
            </>
        );
    }
    return (
        <>
            <li className="nav-item">
                <Link to="register" className="nav-link text-dark">Register</Link>
            </li>
            <li className="nav-item">
                <Link to="login" className="nav-link text-dark">Login</Link>
            </li>
        </>
    );
}

interface IUserInfoProps {
    jwt: DecodedJWT,
    refreshToken: IRefreshToken,
}

const UserInfo = (props: IUserInfoProps) => {
    return (
        <>
            {props.jwt.name}
        </>
    );
}

export default IdentityHeader;

// video-archiver-vue/src/components/IdentityHeader.vue
<script setup lang="ts">
import { useIdentityStore } from '@/stores/identityStore';
import UserInfo from './UserInfo.vue';
const store = useIdentityStore();
</script>

<template>
    <template v-if="store.jwt && store.refreshToken">
        <li class="nav-item">
            <Link to="info" class="nav-link text-dark">
            <UserInfo />
            </Link>
        </li>
        <li class="nav-item">
            <!-- <a onClick={(e)=> {
                e.preventDefault();
                logout();
                }} class="nav-link text-dark" href="#">Logout</a> -->
        </li>
    </template>
    <template v-else>
        <li class="nav-item">
                <RouterLink to="register" class="nav-link text-dark">Register</RouterLink>
            </li>
            <li class="nav-item">
                <RouterLink to="login" class="nav-link text-dark">Login</RouterLink>
            </li>
    </template>
</template>
