// video-archiver-vue/src/components/AuthorSummary.vue
<script setup lang="ts">
import type { IAuthor } from '@/dto/IAuthor';
import {getNameDisplay} from '@/dto/IAuthor';

export interface IProps {
    author: IAuthor,
}

defineProps<IProps>();
</script>

<template>
    <div class="gap-1 d-flex">
        <div class="d-inline-block">
            <img v-if="author.profileImages?.length ?? 0 > 0" v-lazy="author.profileImages![0].url" width="40" height="40"
                alt="Author profile image" />
        </div>
        <div class="d-inline-block">
            <a v-if="author.urlOnPlatform" :href="author.urlOnPlatform">{{ getNameDisplay(author) }}</a>
            <span v-else>{{ getNameDisplay(author) }}</span>
        </div>
    </div>
</template>

// video-archiver-react/src/components/AuthorSummary.tsx
import { IAuthor, getNameDisplay } from "../dto/IAuthor";

interface IProps {
    author: IAuthor,
}

const AuthorSummary = (props: IProps) => {
    return (
        <div className="gap-1 d-flex">
            <div className="d-inline-block">
                {(props.author.profileImages?.length ?? 0) > 0 ?
                    // eslint-disable-next-line jsx-a11y/img-redundant-alt
                    <img loading="lazy" src={props.author.profileImages![0].url} width={40} height={40} alt="Profile image" /> :
                    <div>No profile image</div>}
            </div>
            <div className="d-inline-block">
                {props.author.urlOnPlatform ?
                    <a href={props.author.urlOnPlatform}>{getNameDisplay(props.author)}</a> :
                    <span>{getNameDisplay(props.author)}</span>}
            </div>
        </div>
    );
}

export default AuthorSummary;
