// video-archiver-vue/src/components/PaginationButton.vue
<script setup lang="ts">
export interface IProps {
    page: number,
    currentPage: number,
}

const props = defineProps<IProps>();
</script>

<template>
    <button @click="$emit('pageChange', page)"
        :class="{ btn: true, 'btn-primary': page === currentPage, 'btn-outline-primary': page !== currentPage }">
        <slot>
            {{ page + 1 }}
        </slot>
    </button>
</template>

// video-archiver-react/src/components/PaginationButton.tsx
import classNames from "classnames";
import { ReactNode } from "react";

interface IProps {
    page: number,
    currentPage: number,
    onPageChange: PageChangeAction,
    children?: ReactNode
}

export type PageChangeAction = ((page: number) => Promise<void>) | ((page: number) => void);

const PaginationButton = (props: IProps) => {
    return <button onClick={_ => props.onPageChange(props.page)}
        className={classNames({
            btn: true,
            'btn-primary': props.page === props.currentPage,
            'btn-outline-primary': props.page !== props.currentPage
        })}>
        {props.children ?? <>{props.page + 1}</>}
    </button>
}

export default PaginationButton;
